myblog/blog/urls.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# author: Weishi Li
# time: 2019-03-12

from django.urls import path

from . import  views

urlpatterns = [
    path('index/', views.index),
    path('article/<article_id>', views.article_page, name='article_page'),
    path('edit/', views.edit_page),
]

myblog/blog2/urls.py
# !/usr/bin/env python
# -*- coding: utf-8 -*-
# author: Weishi Li
# time: 2019-03-12

from django.urls import path

from . import  views

urlpatterns = [
    path('index/', views.index),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('blog2/', include('blog2.urls')),
]

myblog/blog/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=32, default="Title")
    content = models.TextField(null=True)

    def __str__(self):
        return self.title

myblog/blog2/models.py
from django.db import models

# Create your models here.

myblog/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models

# Django中所有的请求都用函数处理

def index(request):
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})

def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article': article})

def edit_page(request):
    return render(request, 'blog/edit_page.html')

myblog/blog2/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Django中所有的请求都用函数处理

def index(request):
    return render(request, 'blog2/index.html')

myblog/blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>article_page</title>
</head>
<body>
<h1>{{ article.title }}</h1>
<br/>
<h3>{{ article.content }}</h3>
<br/><br/>
<a href="">modify</a>
</body>
</html>

myblog/blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit_page</title>
</head>
<body>
<form action="" method="post">

    <label>article_name
        <input type="text" name="title">
    </label>
    <br/>

    <label>article_content
        <input type="text" name="content">
    </label>
    <br/>

    <input type="submit" value="submit">

</form>
</body>
</html>

myblog/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>
    <a href="">new article</a>
</h1>

{% for article in articles %}
    <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
    <br/>
{% endfor %}

</body>
</html>

myblog/blog2/templates/blog2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Hello, blog2!</h1>
</body>
</html>